export const SYSTEM_CONSTANTS = {
  CURRENCY: 'PKR',
  LOCATION: 'Pakistan',
  REGION: [
    'Lahore',
    'Karachi',
    'Islamabad',
    'Multan',
    'Faisalabad',
    'Rawalpindi',
    'Peshawar',
    'Quetta',
    'Sialkot',
    'Gujranwala',
    'Hyderabad',
    'Sukkur',
    'Bahawalpur',
    'Sargodha',
    'Sahiwal',
    'Dera Ghazi Khan',
    'Mardan',
    'Swat',
    'Abbottabad',
    'Kohat',
    'Dera Ismail Khan',
    'Chitral',
    'Gilgit',
    'Skardu',
    'Muzaffarabad',
    'Mirpur',
    'Kotli',
    'Bhimber',
    'Neelum Valley',
    'Astore',
    'Diamer',
    'Ghizer',
    'Hunza',
    'Nagar',
    'Shigar',
    'Skardu',
    'Burewala',
    'Chiniot',
    'Jhang',
    'Toba Tek Singh',
    'Vehari',
    'Khanewal',
    'Lodhran',
    'Bahawalnagar',
    'Rahim Yar Khan',
    'Layyah',
    'Rajanpur',
  ],
  DEFAULT_TAX_RATE: 0.15, // 15% VAT in Pakistan
};

export const ROLES = {
  ADMIN: 'admin',
  DRIVER: 'driver',
  USER: 'user',
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    'users.manage',
    'drivers.manage',
    'services.manage',
    'bookings.manage',
    'payments.manage',
    'reports.view',
  ],
  [ROLES.DRIVER]: [
    'tasks.view',
    'tasks.update',
    'payments.cod.process',
    'profile.view',
  ],
  [ROLES.USER]: [
    'bookings.create',
    'bookings.view',
    'payments.create',
    'profile.view',
  ],
};
